apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-bank-api-deployment
  labels:
    app: go-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-bank-api
  template:
    metadata:
      labels:
        app: go-bank-api
    spec:
      containers:
      - name: go-bank-api
        image: 148761677692.dkr.ecr.ap-northeast-3.amazonaws.com/go-bank:9ff32dcf6f6155a311174fe81f109820a7f9f1b8
        ports:
        - containerPort: 8080